export type OptionsType = {
  url: string,
  width: number,
  height: number,
  fullPage: boolean,
  landscape: boolean,
  format: string,
  scale: number,
  quality: number,
  delay: number,
  type: ['png' | 'jpeg' | 'pdf'],
  agent: string,
  force: boolean,
  headers?: Object,
  cookies?: Array<Object>,
  selector?: string,
  selectorOptions: Object,
  emulateMedia?: string,
  printBackground?: boolean,
  lang?: string,
  s3?: string
 }
